name: C application Receiver

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install flake8
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: run
      run: |
        g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
        python ./test_BMS_datastream.py | ./testchecker 
        
    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
   
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
