# This is a basic workflow to help you get started with Actions

name: Console Redirect

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
 workflow_run:
    workflows: ["Python application"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Redirect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
     - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
        python-version: 3.9
        
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         
     - name: Lint with flake8
       run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
     
       
      # Runs a single command using the runners shell
     - name: Console Redirect
       run:  |
         cd ..
         python test_BMS_datastream.py > sudo output.txt
       
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v2
       with:
        name: output
        path: ./*.txt
        retention-days: 1
